export const apiPermissions = {
    "/api/user/update": ["CUSTOMER", "ADMIN"],
    "/api/user/change-password": ["CUSTOMER"],
    "/api/user/profile": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/auth/logout": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/file/image": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/lender/add": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/lender/update": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/lender/delete/:id": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/content/comment/:id": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/content/comment/like/:commentId": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/credit-card": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/credit-card/update/:id": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/notification/list": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/notification/read/:userId": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/notification/delete/:userId": ["ADMIN", "CUSTOMER", "CREATE"],
    "/api/credit-card/detail/:ccId": ["PUBLIC"],
    "/api/lender/detail/:lenderId": ["PUBLIC"],
    "/api/content/detail/:contentId": ["PUBLIC"],
    // "/api/content/comment/replies/:commentId": ["ADMIN", "CUSTOMER", "CREATE"],
    // "/api/content/comment/list/:commentId": ["ADMIN", "CUSTOMER", "CREATE"],
};
